// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_getImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// web->srv
type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// srv->web
type Response struct {
	// 错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	// 错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	// pix,保管图像的像素色彩信息,顺序为R,G,B,A
	Pix []uint32 `protobuf:"varint,3,rep,packed,name=pix,proto3" json:"pix,omitempty"`
	// Stride,表示pix中每行像素占用的字节数
	Stride               int64          `protobuf:"varint,4,opt,name=stride,proto3" json:"stride,omitempty"`
	Min                  *ResponsePoint `protobuf:"bytes,5,opt,name=min,proto3" json:"min,omitempty"`
	Max                  *ResponsePoint `protobuf:"bytes,6,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetPix() []uint32 {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *ResponsePoint {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *ResponsePoint {
	if m != nil {
		return m.Max
	}
	return nil
}

// point,表示图像的范围
type ResponsePoint struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponsePoint) Reset()         { *m = ResponsePoint{} }
func (m *ResponsePoint) String() string { return proto.CompactTextString(m) }
func (*ResponsePoint) ProtoMessage()    {}
func (*ResponsePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1, 0}
}

func (m *ResponsePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePoint.Unmarshal(m, b)
}
func (m *ResponsePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePoint.Marshal(b, m, deterministic)
}
func (m *ResponsePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePoint.Merge(m, src)
}
func (m *ResponsePoint) XXX_Size() int {
	return xxx_messageInfo_ResponsePoint.Size(m)
}
func (m *ResponsePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePoint.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePoint proto.InternalMessageInfo

func (m *ResponsePoint) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ResponsePoint) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.getImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getImageCd.Response")
	proto.RegisterType((*ResponsePoint)(nil), "go.micro.srv.getImageCd.Response.point")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x8d, 0xd9, 0x76, 0x75, 0x54, 0x90, 0x41, 0x34, 0xac, 0x08, 0xb5, 0x1e, 0xec, 0x29,
	0xc2, 0x7a, 0xf2, 0x2c, 0x22, 0x5e, 0xe3, 0x5d, 0xa8, 0x76, 0x28, 0x01, 0xdb, 0xc4, 0x24, 0x95,
	0xec, 0x8f, 0x17, 0xa4, 0xd9, 0xae, 0x37, 0x95, 0x3d, 0x65, 0xbe, 0x61, 0x5e, 0xf2, 0xe6, 0x05,
	0xce, 0xad, 0x33, 0xc1, 0xdc, 0x50, 0xac, 0x3b, 0xfb, 0x4e, 0x9b, 0x53, 0xa6, 0x2e, 0x9e, 0xb5,
	0x46, 0x76, 0xfa, 0xcd, 0x19, 0xe9, 0xdd, 0xa7, 0x6c, 0x29, 0x3c, 0x75, 0x75, 0x4b, 0xf7, 0x4d,
	0x79, 0x01, 0x73, 0x45, 0x1f, 0x03, 0xf9, 0x80, 0x08, 0xb3, 0x61, 0xd0, 0x8d, 0x60, 0x05, 0xab,
	0xf6, 0x55, 0xaa, 0xcb, 0x2f, 0x06, 0x7b, 0x8a, 0xbc, 0x35, 0xbd, 0x27, 0x3c, 0x81, 0x8c, 0x9c,
	0xeb, 0xcd, 0x34, 0xb1, 0x06, 0x3c, 0x85, 0x9c, 0x9c, 0xeb, 0x7c, 0x2b, 0x76, 0x53, 0x7b, 0x22,
	0x3c, 0x06, 0x6e, 0x75, 0x14, 0xbc, 0xe0, 0xd5, 0x91, 0x1a, 0xcb, 0x71, 0xd2, 0x07, 0xa7, 0x1b,
	0x12, 0xb3, 0x82, 0x55, 0x5c, 0x4d, 0x84, 0x77, 0xc0, 0x3b, 0xdd, 0x8b, 0xac, 0x60, 0xd5, 0xc1,
	0xf2, 0x5a, 0xfe, 0x62, 0x55, 0x6e, 0x7c, 0x48, 0x6b, 0x74, 0x1f, 0xd4, 0xa8, 0x49, 0xd2, 0x3a,
	0x8a, 0x7c, 0x5b, 0x69, 0x1d, 0x17, 0x57, 0x90, 0x25, 0xc2, 0x43, 0x60, 0x31, 0xad, 0xc4, 0x15,
	0x8b, 0x23, 0xad, 0xd2, 0x26, 0x5c, 0xb1, 0xd5, 0xf2, 0x05, 0xe6, 0x0f, 0xeb, 0x20, 0xf1, 0x19,
	0xe0, 0xf1, 0xe7, 0x46, 0x2c, 0xfe, 0x78, 0x2b, 0xc5, 0xb9, 0xb8, 0xfc, 0xd7, 0x4d, 0xb9, 0xf3,
	0x9a, 0xa7, 0xef, 0xb9, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x5f, 0xa8, 0xcb, 0xbd, 0x01,
	0x00, 0x00,
}
