// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_getUserInfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// web->srv
type Request struct {
	// sessionId
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

// srv->web
type Response struct {
	// 错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	// 错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	// user_id
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// name
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// mobile
	Mobile string `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// real_name
	RealName string `protobuf:"bytes,6,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	// id_card
	IdCard string `protobuf:"bytes,7,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	// avatar_url
	AvatarUrl            string   `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Response) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Response) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Response) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.getUserInfo.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getUserInfo.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xad, 0xee, 0xf6, 0xcf, 0x78, 0x1b, 0xc4, 0x0d, 0xae, 0x82, 0xf6, 0xa2, 0xa7, 0x08,
	0xfa, 0x11, 0x44, 0xa4, 0x17, 0x0f, 0x85, 0xf5, 0x5a, 0xb2, 0x9b, 0xb1, 0x04, 0xda, 0xa6, 0x4e,
	0xda, 0xc5, 0xcf, 0xe9, 0x27, 0x92, 0x26, 0x95, 0x3d, 0xb9, 0xa7, 0xe4, 0xfd, 0xe6, 0xbd, 0x40,
	0xde, 0xc0, 0xba, 0x67, 0x3b, 0xd8, 0x47, 0xfa, 0x56, 0x6d, 0xdf, 0xd0, 0xdf, 0x29, 0x3d, 0x45,
	0x51, 0x5b, 0xd9, 0x9a, 0x1d, 0x5b, 0xe9, 0x78, 0x2f, 0x6b, 0x1a, 0x36, 0x8e, 0xb8, 0xe8, 0x3e,
	0x6d, 0x7e, 0x0f, 0x49, 0x49, 0x5f, 0x23, 0xb9, 0x01, 0xaf, 0x21, 0x73, 0xe4, 0x9c, 0xb1, 0x5d,
	0xa1, 0x45, 0x74, 0x1b, 0x3d, 0x64, 0xe5, 0x01, 0xe4, 0x3f, 0x11, 0xa4, 0x25, 0xb9, 0xde, 0x76,
	0x8e, 0xf0, 0x02, 0x96, 0xc4, 0xdc, 0xd9, 0xd9, 0x16, 0x04, 0x5e, 0x42, 0x4c, 0xcc, 0xad, 0xab,
	0xc5, 0xa9, 0xc7, 0xb3, 0xc2, 0x15, 0x24, 0xa3, 0x23, 0xae, 0x8c, 0x16, 0x67, 0x61, 0x30, 0xc9,
	0x42, 0x23, 0xc2, 0xa2, 0x53, 0x2d, 0x89, 0x85, 0xa7, 0xfe, 0x3e, 0x3d, 0xd2, 0xda, 0xad, 0x69,
	0x48, 0x2c, 0x83, 0x37, 0x28, 0x5c, 0x43, 0xc6, 0xa4, 0x9a, 0xca, 0x07, 0x62, 0x3f, 0x4a, 0x27,
	0xf0, 0x3e, 0x85, 0x56, 0x90, 0x18, 0x5d, 0xed, 0x14, 0x6b, 0x91, 0x84, 0x94, 0xd1, 0x2f, 0x8a,
	0x35, 0xde, 0x00, 0xa8, 0xbd, 0x1a, 0x14, 0x57, 0x23, 0x37, 0x22, 0x0d, 0x9f, 0x0a, 0x64, 0xc3,
	0xcd, 0x93, 0x82, 0xe4, 0x35, 0x14, 0x85, 0x1f, 0x70, 0xfe, 0x76, 0xe8, 0x05, 0xef, 0xe4, 0x7f,
	0x95, 0xc9, 0xb9, 0xaf, 0xab, 0xfc, 0x98, 0x25, 0x14, 0x95, 0x9f, 0x6c, 0x63, 0xbf, 0x81, 0xe7,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xc5, 0x63, 0xe8, 0xa0, 0x01, 0x00, 0x00,
}
