// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_getArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	//错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	//错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	//返回的数据
	Data                 []*ResponseAddress `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*ResponseAddress {
	if m != nil {
		return m.Data
	}
	return nil
}

//返回的数据类型
type ResponseAddress struct {
	AId                  int32    `protobuf:"varint,1,opt,name=aId,proto3" json:"aId,omitempty"`
	AName                string   `protobuf:"bytes,2,opt,name=aName,proto3" json:"aName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseAddress) Reset()         { *m = ResponseAddress{} }
func (m *ResponseAddress) String() string { return proto.CompactTextString(m) }
func (*ResponseAddress) ProtoMessage()    {}
func (*ResponseAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1, 0}
}

func (m *ResponseAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAddress.Unmarshal(m, b)
}
func (m *ResponseAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAddress.Marshal(b, m, deterministic)
}
func (m *ResponseAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAddress.Merge(m, src)
}
func (m *ResponseAddress) XXX_Size() int {
	return xxx_messageInfo_ResponseAddress.Size(m)
}
func (m *ResponseAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAddress proto.InternalMessageInfo

func (m *ResponseAddress) GetAId() int32 {
	if m != nil {
		return m.AId
	}
	return 0
}

func (m *ResponseAddress) GetAName() string {
	if m != nil {
		return m.AName
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.getArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getArea.Response")
	proto.RegisterType((*ResponseAddress)(nil), "go.micro.srv.getArea.Response.address")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x85, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0x91,
	0xf4, 0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xa2, 0x32, 0xbd, 0xf4, 0xd4, 0x12,
	0xc7, 0xa2, 0xd4, 0x44, 0x25, 0x4e, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xa5,
	0xe5, 0x8c, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x22, 0x5c, 0xac,
	0xa9, 0x45, 0x45, 0x79, 0xf9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x18,
	0x17, 0x5b, 0x6a, 0x51, 0x51, 0x6e, 0x71, 0xba, 0x04, 0x13, 0x58, 0x18, 0xca, 0x13, 0xb2, 0xe2,
	0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x36, 0x52, 0xd3, 0xc3, 0x66,
	0x95, 0x1e, 0xcc, 0x6c, 0xbd, 0xc4, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0xe2, 0x20, 0xb0, 0x1e, 0x29,
	0x43, 0x2e, 0x76, 0xa8, 0x80, 0x90, 0x00, 0x17, 0x73, 0xa2, 0x67, 0x0a, 0xd8, 0x4a, 0xd6, 0x20,
	0x10, 0x13, 0xe4, 0x8c, 0x44, 0xbf, 0xc4, 0xdc, 0x54, 0xa8, 0x7d, 0x10, 0x8e, 0x51, 0x28, 0x17,
	0xbb, 0x2b, 0xc4, 0x6f, 0x42, 0x5e, 0x5c, 0xec, 0xee, 0x10, 0xf3, 0x85, 0x64, 0x71, 0x59, 0x0b,
	0xf6, 0x9e, 0x94, 0x1c, 0x7e, 0x57, 0x29, 0x31, 0x24, 0xb1, 0x81, 0x03, 0xca, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x8c, 0x55, 0x70, 0xa6, 0x47, 0x01, 0x00, 0x00,
}
